/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import view.pesquisas.JDlgClientesPesquisa;
import aulas.*;
import bean.ClientesJmbv;
import dao.Clientes_DAO;
import java.awt.Color;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import tools.Util;

/**
 *
 * @author u05366703158
 */
public class JDlgClientes extends javax.swing.JDialog {
    
    private boolean incluindo;
    public boolean pesquisado;
    /**
     * Creates new form JDlgClientes
     */
    public JDlgClientes(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        desabilitar();
        jBtnConfirmar_jmbv.setEnabled(false);
        jBtnCancelar_jmbv.setEnabled(false);
        setLocationRelativeTo(null);
        setTitle("Cadastro de Clientes");
        
        jBtnAlterar_jmbv.setEnabled(false);
    }
    
    public void habilitar() {
        Util.habilitar(true, jTxtCodigo_jmbv, jTxtNome_jmbv, jFmtCpf_jmbv,jFmtCep_jmbv,jTxtComplemento_jmbv,jTxtCidade_jmbv,jTxtContato_jmbv,jTxtEmail_jmbv,jTxtEndereco_jmbv,jTxtEstado_jmbv,jFmtCelular_jmbv, jFmtRg_jmbv,jCboSexo_jmbv,jTxtBairro_jmbv,jFmtDataNascimento_jmbv, jBtnConfirmar_jmbv, jBtnCancelar_jmbv);
        Util.habilitar(false, jBtnIncluir_jmbv, jBtnAlterar_jmbv, jBtnExcluir_jmbv, jBtnAlterar_jmbv);
        
        /*
        jTxtCodigo_jmbv.setEnabled(true);
        jTxtNome_jmbv.setEnabled(true);
        jFmtCpf_jmbv.setEnabled(true);     
        jFmtDataNascimento_jmbv.setEnabled(true);
        
        jFmtCep_jmbv.setEnabled(true); 
        jTxtComplemento_jmbv.setEnabled(true);
        jTxtCidade_jmbv.setEnabled(true);
        jTxtContato_jmbv.setEnabled(true);
        jTxtEmail_jmbv.setEnabled(true);
        jTxtEndereco_jmbv.setEnabled(true);
        jTxtEstado_jmbv.setEnabled(true);
        jFmtCelular_jmbv.setEnabled(true);
        jFmtRg_jmbv.setEnabled(true);
        jCboSexo_jmbv.setEnabled(true);
        jTxtBairro_jmbv.setEnabled(true);

        
        jBtnConfirmar_jmbv.setEnabled(true);
        jBtnCancelar_jmbv.setEnabled(true);
        
        jBtnIncluir_jmbv.setEnabled(false);
        jBtnAlterar_jmbv.setEnabled(false);
        jBtnExcluir_jmbv.setEnabled(false);
        jBtnPesquisa_jmbv.setEnabled(false);
        */
    
}
    public void desabilitar(){
        Util.habilitar(false, jTxtCodigo_jmbv, jTxtNome_jmbv, jFmtCpf_jmbv,jFmtCep_jmbv,jTxtComplemento_jmbv,jTxtCidade_jmbv,jTxtContato_jmbv,jTxtEmail_jmbv,jTxtEndereco_jmbv,jTxtEstado_jmbv,jFmtCelular_jmbv, jFmtRg_jmbv,jCboSexo_jmbv,jTxtBairro_jmbv,jFmtDataNascimento_jmbv, jBtnConfirmar_jmbv, jBtnCancelar_jmbv);
        Util.habilitar(true, jBtnIncluir_jmbv, jBtnAlterar_jmbv, jBtnExcluir_jmbv, jBtnAlterar_jmbv);
        /*
        jTxtCodigo_jmbv.setEnabled(false);
        jTxtNome_jmbv.setEnabled(false);
        jFmtCpf_jmbv.setEnabled(false);
        jFmtDataNascimento_jmbv.setEnabled(false);
        
        jFmtCep_jmbv.setEnabled(false); 
        jTxtComplemento_jmbv.setEnabled(false);
        jTxtCidade_jmbv.setEnabled(false);
        jTxtContato_jmbv.setEnabled(false);
        jTxtEmail_jmbv.setEnabled(false);
        jTxtEndereco_jmbv.setEnabled(false);
        jTxtEstado_jmbv.setEnabled(false);
        jFmtCelular_jmbv.setEnabled(false);
        jFmtRg_jmbv.setEnabled(false);
        jCboSexo_jmbv.setEnabled(false);
        jTxtBairro_jmbv.setEnabled(false);
        
        jBtnConfirmar_jmbv.setEnabled(false);
        jBtnCancelar_jmbv.setEnabled(false);
         
        jBtnIncluir_jmbv.setEnabled(true);
        jBtnAlterar_jmbv.setEnabled(true);
        jBtnExcluir_jmbv.setEnabled(true);
        jBtnPesquisa_jmbv.setEnabled(true);
        */
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jLabel1 = new javax.swing.JLabel();
        jTxtCodigo_jmbv = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTxtNome_jmbv = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jBtnIncluir_jmbv = new javax.swing.JButton();
        jBtnAlterar_jmbv = new javax.swing.JButton();
        jBtnExcluir_jmbv = new javax.swing.JButton();
        jBtnConfirmar_jmbv = new javax.swing.JButton();
        jBtnCancelar_jmbv = new javax.swing.JButton();
        jBtnPesquisa_jmbv = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jFmtDataNascimento_jmbv = new javax.swing.JFormattedTextField();
        jLabel9 = new javax.swing.JLabel();
        jTxtContato_jmbv = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jTxtEndereco_jmbv = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTxtBairro_jmbv = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTxtComplemento_jmbv = new javax.swing.JTextField();
        jTxtEstado_jmbv = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jTxtCidade_jmbv = new javax.swing.JTextField();
        jTxtEmail_jmbv = new javax.swing.JTextField();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jCboSexo_jmbv = new javax.swing.JComboBox<>();
        jFmtCelular_jmbv = new javax.swing.JFormattedTextField();
        jFmtCpf_jmbv = new javax.swing.JFormattedTextField();
        jFmtCep_jmbv = new javax.swing.JFormattedTextField();
        jFmtRg_jmbv = new javax.swing.JFormattedTextField();

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("Código");

        jLabel2.setText("Nome");

        jLabel4.setText("CpF");

        jLabel5.setText("CEP");

        jLabel6.setText("Contato");

        jBtnIncluir_jmbv.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/incluir.png"))); // NOI18N
        jBtnIncluir_jmbv.setText("Incluir");
        jBtnIncluir_jmbv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnIncluir_jmbvActionPerformed(evt);
            }
        });

        jBtnAlterar_jmbv.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/alterar.png"))); // NOI18N
        jBtnAlterar_jmbv.setText("Alterar");
        jBtnAlterar_jmbv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnAlterar_jmbvActionPerformed(evt);
            }
        });

        jBtnExcluir_jmbv.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Excluir.png"))); // NOI18N
        jBtnExcluir_jmbv.setText("Excluir");
        jBtnExcluir_jmbv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnExcluir_jmbvActionPerformed(evt);
            }
        });

        jBtnConfirmar_jmbv.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/confirmar.png"))); // NOI18N
        jBtnConfirmar_jmbv.setText("Confirmar");
        jBtnConfirmar_jmbv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnConfirmar_jmbvActionPerformed(evt);
            }
        });

        jBtnCancelar_jmbv.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cancelar.png"))); // NOI18N
        jBtnCancelar_jmbv.setText("Cancelar");
        jBtnCancelar_jmbv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCancelar_jmbvActionPerformed(evt);
            }
        });

        jBtnPesquisa_jmbv.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/pesquisar.png"))); // NOI18N
        jBtnPesquisa_jmbv.setText("Pesquisar");
        jBtnPesquisa_jmbv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnPesquisa_jmbvActionPerformed(evt);
            }
        });

        jLabel8.setText("Sexo");

        try {
            jFmtDataNascimento_jmbv.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFmtDataNascimento_jmbv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFmtDataNascimento_jmbvActionPerformed(evt);
            }
        });

        jLabel9.setText("Data de Nascimento");

        jTxtContato_jmbv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtContato_jmbvActionPerformed(evt);
            }
        });

        jLabel10.setText("Endereço");

        jTxtEndereco_jmbv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtEndereco_jmbvActionPerformed(evt);
            }
        });

        jLabel11.setText("Celular");

        jTxtBairro_jmbv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtBairro_jmbvActionPerformed(evt);
            }
        });

        jLabel12.setText("Bairro");

        jLabel13.setText("Complemento");

        jTxtComplemento_jmbv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtComplemento_jmbvActionPerformed(evt);
            }
        });

        jTxtEstado_jmbv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtEstado_jmbvActionPerformed(evt);
            }
        });

        jLabel14.setText("Estado");

        jLabel15.setText("Cidade");

        jTxtCidade_jmbv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtCidade_jmbvActionPerformed(evt);
            }
        });

        jTxtEmail_jmbv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTxtEmail_jmbvActionPerformed(evt);
            }
        });

        jLabel16.setText("E-mail");

        jLabel17.setText("RG");

        jCboSexo_jmbv.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Masculino", "Feminino" }));
        jCboSexo_jmbv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCboSexo_jmbvActionPerformed(evt);
            }
        });

        try {
            jFmtCelular_jmbv.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            jFmtCpf_jmbv.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFmtCpf_jmbv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFmtCpf_jmbvActionPerformed(evt);
            }
        });

        try {
            jFmtCep_jmbv.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        try {
            jFmtRg_jmbv.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###-#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFmtRg_jmbv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFmtRg_jmbvActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jTxtContato_jmbv, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jFmtCpf_jmbv, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(jFmtCep_jmbv, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jTxtNome_jmbv, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8)
                                    .addComponent(jCboSexo_jmbv, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jFmtDataNascimento_jmbv)
                                    .addComponent(jLabel9)))
                            .addComponent(jLabel1)
                            .addComponent(jTxtCodigo_jmbv, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel13)
                                        .addComponent(jTxtComplemento_jmbv, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel14)
                                        .addComponent(jTxtEstado_jmbv, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(jLabel16)
                                        .addComponent(jTxtEmail_jmbv, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(7, 7, 7)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel17)
                                        .addComponent(jFmtRg_jmbv, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel10)
                                        .addComponent(jTxtEndereco_jmbv, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel11)
                                        .addComponent(jFmtCelular_jmbv, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jTxtBairro_jmbv, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel12))
                                    .addGap(5, 5, 5)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel15)
                                        .addComponent(jTxtCidade_jmbv, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jBtnIncluir_jmbv)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnAlterar_jmbv)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnExcluir_jmbv)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnConfirmar_jmbv, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnCancelar_jmbv)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jBtnPesquisa_jmbv)))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTxtCodigo_jmbv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTxtNome_jmbv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCboSexo_jmbv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(29, 29, 29))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jFmtDataNascimento_jmbv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jFmtCpf_jmbv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFmtCep_jmbv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxtContato_jmbv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(41, 41, 41)
                                .addComponent(jTxtEndereco_jmbv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jLabel10)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTxtComplemento_jmbv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel13)
                                .addGap(29, 29, 29))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jFmtCelular_jmbv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTxtCidade_jmbv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel15))
                                .addGap(29, 29, 29))
                            .addComponent(jTxtBairro_jmbv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTxtEstado_jmbv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jTxtEmail_jmbv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jFmtRg_jmbv, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel14)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel16)
                                        .addComponent(jLabel17)))
                                .addGap(29, 29, 29)))))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jBtnAlterar_jmbv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBtnConfirmar_jmbv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBtnExcluir_jmbv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jBtnPesquisa_jmbv, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jBtnCancelar_jmbv, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jBtnIncluir_jmbv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

/////////////////////////////////////////////////////////////////////////BOTÕES////////////////////////////////////////////////////////////////////////
    
    private void jBtnIncluir_jmbvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnIncluir_jmbvActionPerformed
        // TODO add your handling code here:
        Util.limparCampos(jTxtCodigo_jmbv, jTxtNome_jmbv, jFmtCpf_jmbv, jFmtDataNascimento_jmbv, jFmtCep_jmbv, jTxtComplemento_jmbv, jTxtCidade_jmbv, jTxtContato_jmbv, jTxtEmail_jmbv, jTxtEndereco_jmbv, jTxtEstado_jmbv, jFmtCelular_jmbv, jFmtRg_jmbv, jCboSexo_jmbv, jTxtBairro_jmbv);
        habilitar();
        
        incluindo = true;
    }//GEN-LAST:event_jBtnIncluir_jmbvActionPerformed

    
    private void jBtnAlterar_jmbvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnAlterar_jmbvActionPerformed
        // TODO add your handling code here:
        habilitar();
        
        incluindo = false;
    }//GEN-LAST:event_jBtnAlterar_jmbvActionPerformed

    private void jBtnConfirmar_jmbvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnConfirmar_jmbvActionPerformed
        // TODO add your handling code here:
        
        ClientesJmbv clientes = viewBean();
        Clientes_DAO clientes_DAO = new Clientes_DAO();//executa o dao
        //boolean pra incluir ou alterar
        if(incluindo == true){
        clientes_DAO.insert(clientes);
        //clientes_DAO.insert(viewBean());//pra fazer direto
        }else{
        clientes_DAO.update(clientes);
        }
        desabilitar();
        Util.limparCampos(jTxtCodigo_jmbv, jTxtNome_jmbv, jFmtCpf_jmbv, jFmtDataNascimento_jmbv, jFmtCep_jmbv, jTxtComplemento_jmbv, jTxtCidade_jmbv, jTxtContato_jmbv, jTxtEmail_jmbv, jTxtEndereco_jmbv, jTxtEstado_jmbv, jFmtCelular_jmbv, jFmtRg_jmbv, jCboSexo_jmbv, jTxtBairro_jmbv);//opcional
        jBtnAlterar_jmbv.setEnabled(false);
    }//GEN-LAST:event_jBtnConfirmar_jmbvActionPerformed

    private void jBtnCancelar_jmbvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCancelar_jmbvActionPerformed
        // TODO add your handling code here:
        desabilitar();
        Util.limparCampos(jTxtCodigo_jmbv, jTxtNome_jmbv, jFmtCpf_jmbv, jFmtDataNascimento_jmbv, jFmtCep_jmbv, jTxtComplemento_jmbv, jTxtCidade_jmbv, jTxtContato_jmbv, jTxtEmail_jmbv, jTxtEndereco_jmbv, jTxtEstado_jmbv, jFmtCelular_jmbv, jFmtRg_jmbv, jCboSexo_jmbv, jTxtBairro_jmbv);
    }//GEN-LAST:event_jBtnCancelar_jmbvActionPerformed

    private void jBtnExcluir_jmbvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnExcluir_jmbvActionPerformed
        // TODO add your handling code here:

        //int resp = JOptionPane.showConfirmDialog(null,"Deseja excluir o registro?","Confirmar", JOptionPane.YES_NO_OPTION);//null centraliza no meio do monitor//mensagem//titulo//os botoes
        if(Util.perguntar("Deseja excluir o registro") == true){
        
        
        //if(resp == 0){//0 e o sim
        //if(resp == JOptionPane.YES_OPTION){//constante serve pra deixar  o codigo mais claro//classe usando um metodo estatico, estatico nao precisa instanciar a classe
        
        ClientesJmbv clientes = viewBean();
        Clientes_DAO clientes_DAO = new Clientes_DAO();//executa o dao
        clientes_DAO.delete(clientes);
        
        //clientes_DAO.insert(viewBean());//pra fazer direto
        }else{
            //JOptionPane.showMessageDialog(null,"Exclusão cancelada.","Alerta",2);
            Util.mensagem("Exclusão cancelada.");
        }
        Util.limparCampos(jTxtCodigo_jmbv, jTxtNome_jmbv, jFmtCpf_jmbv, jFmtDataNascimento_jmbv, jFmtCep_jmbv, jTxtComplemento_jmbv, jTxtCidade_jmbv, jTxtContato_jmbv, jTxtEmail_jmbv, jTxtEndereco_jmbv, jTxtEstado_jmbv, jFmtCelular_jmbv, jFmtRg_jmbv, jCboSexo_jmbv, jTxtBairro_jmbv);
    }//GEN-LAST:event_jBtnExcluir_jmbvActionPerformed

    private void jTxtContato_jmbvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtContato_jmbvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtContato_jmbvActionPerformed

    private void jTxtEndereco_jmbvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtEndereco_jmbvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtEndereco_jmbvActionPerformed

    private void jTxtBairro_jmbvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtBairro_jmbvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtBairro_jmbvActionPerformed

    private void jTxtComplemento_jmbvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtComplemento_jmbvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtComplemento_jmbvActionPerformed

    private void jTxtEstado_jmbvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtEstado_jmbvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtEstado_jmbvActionPerformed

    private void jTxtCidade_jmbvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtCidade_jmbvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtCidade_jmbvActionPerformed

    private void jTxtEmail_jmbvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTxtEmail_jmbvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTxtEmail_jmbvActionPerformed

    private void jCboSexo_jmbvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCboSexo_jmbvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCboSexo_jmbvActionPerformed

    private void jFmtDataNascimento_jmbvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFmtDataNascimento_jmbvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFmtDataNascimento_jmbvActionPerformed

    private void jFmtCpf_jmbvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFmtCpf_jmbvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFmtCpf_jmbvActionPerformed

    private void jBtnPesquisa_jmbvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnPesquisa_jmbvActionPerformed
        // TODO add your handling code here:
        
       /*
        String resp = JOptionPane.showInputDialog(null,"Entre com o Código (PK): ");
        Clientes_DAO clientes_DAO = new Clientes_DAO();//executa o dao
        Clientes clientes = (Clientes) clientes_DAO.list(Integer.valueOf(resp));//faz o polimorfismo pro object do list virar clientes//(casting: fala que o clientes que virou object ainda é um clientes)
        
        beanView(clientes);
        */
       
        JDlgClientesPesquisa jDlgClientesPesquisa = new JDlgClientesPesquisa(null, true);
        jDlgClientesPesquisa.setTelaPai(this);
        jDlgClientesPesquisa.setVisible(true);
    }//GEN-LAST:event_jBtnPesquisa_jmbvActionPerformed

    private void jFmtRg_jmbvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFmtRg_jmbvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFmtRg_jmbvActionPerformed

        public ClientesJmbv viewBean(){
            ClientesJmbv clientes = new ClientesJmbv();
        clientes.setIdclientesJmbv(Util.strInt(jTxtCodigo_jmbv.getText()));
        clientes.setNomeJmbv(jTxtNome_jmbv.getText());
        if(jCboSexo_jmbv.getSelectedIndex() == 0){
        clientes.setSexoJmbv("M");
        }else{
        clientes.setSexoJmbv("F");
        }
        clientes.setEnderecoJmbv(jTxtEndereco_jmbv.getText());
        clientes.setCpfJmbv(jFmtCpf_jmbv.getText());    
        clientes.setDataNascimentoJmbv(Util.strDate(jFmtDataNascimento_jmbv.getText()));
        clientes.setCepJmbv(jFmtCep_jmbv.getText());  
        clientes.setNumeroJmbv(jFmtCelular_jmbv.getText());
        clientes.setEstadoJmbv(jTxtEstado_jmbv.getText());
        clientes.setCidadeJmbv(jTxtCidade_jmbv.getText());
        clientes.setBairroJmbv(jTxtBairro_jmbv.getText());
        clientes.setComplementoJmbv(jTxtComplemento_jmbv.getText());
        clientes.setContatoJmbv(jTxtContato_jmbv.getText());
        clientes.setEmailJmbv(jTxtEmail_jmbv.getText());
        clientes.setRgJmbv(jFmtRg_jmbv.getText());
        
        return clientes;
        }
        
        
        public ClientesJmbv beanView(ClientesJmbv clientes){
            
        jTxtCodigo_jmbv.setText(Util.intStr(clientes.getIdclientesJmbv()));
        jTxtNome_jmbv.setText(clientes.getNomeJmbv());
        if(clientes.getSexoJmbv().equals("M")){
        jCboSexo_jmbv.setSelectedIndex(0);
        }else{
        jCboSexo_jmbv.setSelectedIndex(1);
        }
        jTxtEndereco_jmbv.setText(clientes.getNomeJmbv());
        jFmtCpf_jmbv.setText(clientes.getCpfJmbv());
        jFmtDataNascimento_jmbv.setText(Util.dateStr(clientes.getDataNascimentoJmbv()));
        jFmtCep_jmbv.setText(clientes.getCepJmbv());
        jFmtCelular_jmbv.setText(clientes.getNumeroJmbv());
        jTxtEstado_jmbv.setText(clientes.getEstadoJmbv());
        jTxtCidade_jmbv.setText(clientes.getCidadeJmbv());
        jTxtBairro_jmbv.setText(clientes.getBairroJmbv());

        jTxtComplemento_jmbv.setText(clientes.getComplementoJmbv());
        jTxtContato_jmbv.setText(clientes.getContatoJmbv());
        jTxtEmail_jmbv.setText(clientes.getEmailJmbv());
        jFmtRg_jmbv.setText(clientes.getRgJmbv());
        //jFmtDataNascimento.setText(clientes.getDataNascimento());
        
        
        //jChbAtivo.setSelected(clientes.getAtivo().equals("S"));//faz direto numa linha
        
        jBtnAlterar_jmbv.setEnabled(true);
        return clientes;
        }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDlgClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDlgClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDlgClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDlgClientes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDlgClientes dialog = new JDlgClientes(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnAlterar_jmbv;
    private javax.swing.JButton jBtnCancelar_jmbv;
    private javax.swing.JButton jBtnConfirmar_jmbv;
    private javax.swing.JButton jBtnExcluir_jmbv;
    private javax.swing.JButton jBtnIncluir_jmbv;
    private javax.swing.JButton jBtnPesquisa_jmbv;
    private javax.swing.JComboBox<String> jCboSexo_jmbv;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JFormattedTextField jFmtCelular_jmbv;
    private javax.swing.JFormattedTextField jFmtCep_jmbv;
    private javax.swing.JFormattedTextField jFmtCpf_jmbv;
    private javax.swing.JFormattedTextField jFmtDataNascimento_jmbv;
    private javax.swing.JFormattedTextField jFmtRg_jmbv;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTxtBairro_jmbv;
    private javax.swing.JTextField jTxtCidade_jmbv;
    private javax.swing.JTextField jTxtCodigo_jmbv;
    private javax.swing.JTextField jTxtComplemento_jmbv;
    private javax.swing.JTextField jTxtContato_jmbv;
    private javax.swing.JTextField jTxtEmail_jmbv;
    private javax.swing.JTextField jTxtEndereco_jmbv;
    private javax.swing.JTextField jTxtEstado_jmbv;
    private javax.swing.JTextField jTxtNome_jmbv;
    // End of variables declaration//GEN-END:variables
}
