/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import aulas.*;
import bean.ProdutosJmbv;
import bean.VendasJmbv;
import java.awt.Color;
import dao.VendasProduto_DAO;
import bean.VendasProdutoJmbv;
import dao.Produtos_DAO;
import dao.Vendas_DAO;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import tools.Util;
import view.pesquisas.VendasProdutoControle;

/**
 *
 * @author u05366703158
 */
public class JDlgVendasProduto extends javax.swing.JDialog {

    private boolean incluindo;
    private JDlgVendas jDlgVendas;

    /**
     * Creates new form JDlgUsuarios
     */
    public JDlgVendasProduto(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        //desabilitar();
        //jBtnOK.setEnabled(false);
        //jBtnCancelar.setEnabled(false);
        setLocationRelativeTo(null);
        //setTitle("Incluir Produto");

        jTxtValorTotal.setEnabled(false);

        //produtos
        Produtos_DAO produtos_DAO = new Produtos_DAO();
        List listaProdutos = produtos_DAO.listAll();
        for (int i = 0; i < listaProdutos.size(); i++) {
            jCboProduto.addItem((ProdutosJmbv) listaProdutos.get(i));
        }
    }

    public void setTelaPai(JDlgVendas jDlgVendas) {
        this.jDlgVendas = jDlgVendas;//atributo da classe/ parametro que vc esta passando
    }

    public void habilitar() {
        jTxtValorTotal.setEnabled(true);
        jCboProduto.setEnabled(true);
        //jCboProdutos.setEnabled(true);
        jTxtUnitario.setEnabled(true);

        jBtnOK.setEnabled(true);
        jBtnCancelar.setEnabled(true);

    }

    public void desabilitar() {
        jTxtValorTotal.setEnabled(false);
        //jCboProduto.setEnabled(false);
        //jCboProdutos.setEnabled(false);
        //jTxtUnitario.setEnabled(false);

        jBtnOK.setEnabled(false);
        jBtnCancelar.setEnabled(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBtnOK = new javax.swing.JButton();
        jBtnCancelar = new javax.swing.JButton();
        jLblCliente = new javax.swing.JLabel();
        jTxtUnitario = new javax.swing.JTextField();
        jData1 = new javax.swing.JLabel();
        jTxtValorTotal = new javax.swing.JTextField();
        jData2 = new javax.swing.JLabel();
        jData3 = new javax.swing.JLabel();
        jTxtQuantidade = new javax.swing.JTextField();
        jCboProduto = new javax.swing.JComboBox<ProdutosJmbv>();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jBtnOK.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/ok.png"))); // NOI18N
        jBtnOK.setText("OK");
        jBtnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnOKActionPerformed(evt);
            }
        });

        jBtnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cancelar.png"))); // NOI18N
        jBtnCancelar.setText("Cancelar");
        jBtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtnCancelarActionPerformed(evt);
            }
        });

        jLblCliente.setText("Produto");

        jTxtUnitario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTxtUnitarioKeyReleased(evt);
            }
        });

        jData1.setText("Valor Unitário");

        jData2.setText("Valor Total");

        jData3.setText("Quantidade");

        jTxtQuantidade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTxtQuantidadeKeyReleased(evt);
            }
        });

        jCboProduto.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jCboProdutoItemStateChanged(evt);
            }
        });
        jCboProduto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jCboProdutoKeyPressed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLblCliente)
                            .addComponent(jCboProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTxtUnitario, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jData1)))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jBtnOK)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jBtnCancelar))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jData3)
                                .addComponent(jTxtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGap(20, 20, 20)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jData2)
                                .addComponent(jTxtValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLblCliente)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jCboProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jData1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxtUnitario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jData2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxtValorTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jData3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTxtQuantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 153, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBtnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jBtnOK, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void jBtnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnOKActionPerformed
        // TODO add your handling code here:
/*
        VendasProduto vendasProduto = viewBean();

        VendasProduto_DAO vendasProduto_DAO = new VendasProduto_DAO();//executa o dao
        vendasProduto_DAO.insert(vendasProduto);
        if (incluindo == true) {
        } else {
            vendasProduto_DAO.update(vendasProduto);
        }
         */
        Vendas_DAO vendas_DAO = new Vendas_DAO();

        VendasProdutoJmbv vendasProduto = ViewBean();
        if (getTitle().toUpperCase().substring(0, 1).equals("I")) {
//VendasProdutoControle vendprodcon = new VendasProdutoControle();
//codigo suspeito do claudio
/*
    vendas_DAO.insert(vendasProduto);
    Util.mensagem("Registro incluido");
    List lista = vendas_DAO.listAll();
    jDlgVendas.vendasProdutoControle.setList(lista);
             */

            jDlgVendas.vendasProdutoControle.addBean(vendasProduto);

        } else {
//VendasProdutoControle vendprodcon = new VendasProdutoControle();

//codigo suspeito do claudio
/*
    vendas_DAO.update(vendasProduto);
    Util.mensagem("Registro incluido");
    List lista = vendas_DAO.listAll();
    jDlgVendas.vendasProdutoControle.setList(lista);
             */
            jDlgVendas.vendasProdutoControle.updateBean(jDlgVendas.getSelectedRowProd(), vendasProduto);
        }
        desabilitar();
        limparCampos();
        setVisible(false);
    }//GEN-LAST:event_jBtnOKActionPerformed

    private void jBtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtnCancelarActionPerformed
        // TODO add your handling code here:
        desabilitar();
        limparCampos();
        setVisible(false);
    }//GEN-LAST:event_jBtnCancelarActionPerformed

    private void jTxtQuantidadeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtQuantidadeKeyReleased
        // TODO add your handling code here:
        altTotal();
    }//GEN-LAST:event_jTxtQuantidadeKeyReleased

    private void jTxtUnitarioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTxtUnitarioKeyReleased
        // TODO add your handling code here:
        altTotal();
    }//GEN-LAST:event_jTxtUnitarioKeyReleased

    private void jCboProdutoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jCboProdutoKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCboProdutoKeyPressed

    private void jCboProdutoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jCboProdutoItemStateChanged
        // TODO add your handling code here:
        ProdutosJmbv prod = (ProdutosJmbv) jCboProduto.getSelectedItem();
        jTxtUnitario.setText(Util.doubleStr(prod.getPrecoJmbv()));
    }//GEN-LAST:event_jCboProdutoItemStateChanged

    public void limparCampos() {
        //apagar?
        jTxtValorTotal.setText("");
        //ProdutosJmbv prod = (ProdutosJmbv) jCboProduto.getSelectedItem();
        //jTxtUnitario.setText(Util.doubleStr(prod.getPrecoJmbv()));
    }

    public VendasProdutoJmbv ViewBean() {
        VendasProdutoJmbv vendasProd = new VendasProdutoJmbv();
        //vendasProd.setIdvendasProdutoJmbv();
        ProdutosJmbv prod = (ProdutosJmbv) jCboProduto.getSelectedItem();
        vendasProd.setProdutosJmbv(prod);
        Vendas_DAO vendas_DAO = new Vendas_DAO();
        // ve se tem um jeito mais facil de fazer isso
        //VendasJmbv vendas2 = (VendasJmbv) vendas_DAO.list(jDlgVendas.getId());
        //vendasProd.setVendasJmbv(vendas2);
        vendasProd.setValorUnitarioJmbv(Util.strDouble(jTxtUnitario.getText()));
        vendasProd.setQuantidadeJmbv(Util.strInt(jTxtQuantidade.getText()));

        return vendasProd;
    }

    ;
    public VendasProdutoJmbv BeanView(VendasProdutoJmbv vendasProd) {
        //vendasProd.setIdvendasProdutoJmbv();
        ProdutosJmbv produtos = new ProdutosJmbv();
        jCboProduto.setSelectedIndex(produtos.getIdprodutosJmbv());
        jTxtUnitario.setText(Util.doubleStr(vendasProd.getValorUnitarioJmbv()));
        jTxtQuantidade.setText(Util.intStr(vendasProd.getQuantidadeJmbv()));

        return vendasProd;
    }

    ;
    
    public void altTotal() {
        if (!jTxtUnitario.getText().equals("") && !jTxtQuantidade.getText().equals("")) {
            double unit = Util.strDouble(jTxtUnitario.getText());
            int quant = Util.strInt(jTxtQuantidade.getText());
            double total = quant * unit;
            jTxtValorTotal.setText(Util.doubleStr(total));
            //jTxtValorTotal.setText(Util.doubleStr(Util.strInt(jTxtQuantidade.getText()) * Util.strDouble(jTxtUnitario.getText())));
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JDlgVendasProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JDlgVendasProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JDlgVendasProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JDlgVendasProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                JDlgVendasProduto dialog = new JDlgVendasProduto(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBtnCancelar;
    private javax.swing.JButton jBtnOK;
    private javax.swing.JComboBox<ProdutosJmbv> jCboProduto;
    private javax.swing.JLabel jData1;
    private javax.swing.JLabel jData2;
    private javax.swing.JLabel jData3;
    private javax.swing.JLabel jLblCliente;
    private javax.swing.JTextField jTxtQuantidade;
    private javax.swing.JTextField jTxtUnitario;
    private javax.swing.JTextField jTxtValorTotal;
    // End of variables declaration//GEN-END:variables
}
