/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

/**
 *
 * @author jmbvi
 */
public class JFrmPrincipal extends javax.swing.JFrame {

    /**
     * Creates new form JFrmPrincipal
     */
    public JFrmPrincipal() {
        initComponents();
        setTitle("Veterinária");
        setExtendedState(MAXIMIZED_BOTH);//quando esta tudo em maiusculo em C e uma constante
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLblTitulo = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMnuPrincipal_jmbv = new javax.swing.JMenu();
        jMnuClientes_jmbv = new javax.swing.JMenuItem();
        jMnuUsuarios_jmbv = new javax.swing.JMenuItem();
        jMnuProduto_jmbv = new javax.swing.JMenuItem();
        jMnuVendedor_jmbv = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMnuSair_jmbv = new javax.swing.JMenuItem();
        jMnuMovimento = new javax.swing.JMenu();
        jMnuVendas_jmbv = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLblTitulo.setText("Vendas de Produtos de Veterinária");

        jMnuPrincipal_jmbv.setMnemonic('P');
        jMnuPrincipal_jmbv.setText("Principal");
        jMnuPrincipal_jmbv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuPrincipal_jmbvActionPerformed(evt);
            }
        });

        jMnuClientes_jmbv.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        jMnuClientes_jmbv.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/cliente.png"))); // NOI18N
        jMnuClientes_jmbv.setMnemonic('C');
        jMnuClientes_jmbv.setText("Clientes");
        jMnuClientes_jmbv.setToolTipText("");
        jMnuClientes_jmbv.setAutoscrolls(true);
        jMnuClientes_jmbv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuClientes_jmbvActionPerformed(evt);
            }
        });
        jMnuPrincipal_jmbv.add(jMnuClientes_jmbv);

        jMnuUsuarios_jmbv.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_U, java.awt.event.InputEvent.CTRL_MASK));
        jMnuUsuarios_jmbv.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/usuario.png"))); // NOI18N
        jMnuUsuarios_jmbv.setMnemonic('U');
        jMnuUsuarios_jmbv.setText("Usuários");
        jMnuUsuarios_jmbv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuUsuarios_jmbvActionPerformed(evt);
            }
        });
        jMnuPrincipal_jmbv.add(jMnuUsuarios_jmbv);

        jMnuProduto_jmbv.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_P, java.awt.event.InputEvent.CTRL_MASK));
        jMnuProduto_jmbv.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/produto.png"))); // NOI18N
        jMnuProduto_jmbv.setMnemonic('C');
        jMnuProduto_jmbv.setText("Produto");
        jMnuProduto_jmbv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuProduto_jmbvActionPerformed(evt);
            }
        });
        jMnuPrincipal_jmbv.add(jMnuProduto_jmbv);

        jMnuVendedor_jmbv.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_V, java.awt.event.InputEvent.CTRL_MASK));
        jMnuVendedor_jmbv.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/vendedor.png"))); // NOI18N
        jMnuVendedor_jmbv.setText("Vendedor");
        jMnuVendedor_jmbv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuVendedor_jmbvActionPerformed(evt);
            }
        });
        jMnuPrincipal_jmbv.add(jMnuVendedor_jmbv);
        jMnuPrincipal_jmbv.add(jSeparator1);

        jMnuSair_jmbv.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        jMnuSair_jmbv.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/exit.png"))); // NOI18N
        jMnuSair_jmbv.setMnemonic('S');
        jMnuSair_jmbv.setText("Sair");
        jMnuSair_jmbv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuSair_jmbvActionPerformed(evt);
            }
        });
        jMnuPrincipal_jmbv.add(jMnuSair_jmbv);

        jMenuBar1.add(jMnuPrincipal_jmbv);

        jMnuMovimento.setMnemonic('M');
        jMnuMovimento.setText("Movimento");

        jMnuVendas_jmbv.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_A, java.awt.event.InputEvent.CTRL_MASK));
        jMnuVendas_jmbv.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/vendas.png"))); // NOI18N
        jMnuVendas_jmbv.setText("Vendas");
        jMnuVendas_jmbv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMnuVendas_jmbvActionPerformed(evt);
            }
        });
        jMnuMovimento.add(jMnuVendas_jmbv);

        jMenuItem1.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_M, java.awt.event.InputEvent.CTRL_MASK));
        jMenuItem1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/produto.png"))); // NOI18N
        jMenuItem1.setText("VendasProduto");
        jMenuItem1.setToolTipText("");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMnuMovimento.add(jMenuItem1);

        jMenuBar1.add(jMnuMovimento);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addComponent(jLblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 345, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(158, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLblTitulo, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(433, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMnuClientes_jmbvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuClientes_jmbvActionPerformed
        // TODO add your handling code here:
        
        JDlgClientes jDlgClientes = new JDlgClientes(null, true);
        jDlgClientes.setVisible(true);
    }//GEN-LAST:event_jMnuClientes_jmbvActionPerformed

    private void jMnuUsuarios_jmbvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuUsuarios_jmbvActionPerformed
        // TODO add your handling code here: 
        //cria um novo objeto jDlgUsuarios da classe JDlgUsuarios(maiusculo no comeco é classe, minusculo é objeto)
        JDlgUsuarios jDlgUsuarios = new JDlgUsuarios(null, true);
        jDlgUsuarios.setVisible(true);
    }//GEN-LAST:event_jMnuUsuarios_jmbvActionPerformed

                           
    private void jMnuPrincipal_jmbvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuPrincipal_jmbvActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMnuPrincipal_jmbvActionPerformed

    private void jMnuSair_jmbvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuSair_jmbvActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_jMnuSair_jmbvActionPerformed

    private void jMnuProduto_jmbvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuProduto_jmbvActionPerformed
        // TODO add your handling code here:
        
        JDlgProdutosNovo jDlgProdutosNovo = new JDlgProdutosNovo(null, true);
        jDlgProdutosNovo.setVisible(true);
    }//GEN-LAST:event_jMnuProduto_jmbvActionPerformed

    private void jMnuVendedor_jmbvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuVendedor_jmbvActionPerformed
        // TODO add your handling code here:
        JDlgVendedorNovo jDlgVendedorNovo = new JDlgVendedorNovo(null, true);
        jDlgVendedorNovo.setVisible(true);
    }//GEN-LAST:event_jMnuVendedor_jmbvActionPerformed

    private void jMnuVendas_jmbvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMnuVendas_jmbvActionPerformed
        // TODO add your handling code here:
        //JDlgVendas jDlgVendas = new JDlgVendas(null, true);
        //jDlgVendas.setVisible(true);
        
    }//GEN-LAST:event_jMnuVendas_jmbvActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFrmPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFrmPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLblTitulo;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMnuClientes_jmbv;
    private javax.swing.JMenu jMnuMovimento;
    private javax.swing.JMenu jMnuPrincipal_jmbv;
    private javax.swing.JMenuItem jMnuProduto_jmbv;
    private javax.swing.JMenuItem jMnuSair_jmbv;
    private javax.swing.JMenuItem jMnuUsuarios_jmbv;
    private javax.swing.JMenuItem jMnuVendas_jmbv;
    private javax.swing.JMenuItem jMnuVendedor_jmbv;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
