package bean;
// Generated 12/09/2023 08:36:38 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * ProdutosJmbv generated by hbm2java
 */
@Entity
@Table(name="produtos_jmbv"
    ,catalog="db_joao_vilhanueva"
)
public class ProdutosJmbv  implements java.io.Serializable {


     private int idprodutosJmbv;
     private String nomeJmbv;
     private double precoJmbv;
     private String marcaJmbv;
     private Date validadeJmbv;

    public ProdutosJmbv() {
    }

	
    public ProdutosJmbv(int idprodutosJmbv, String nomeJmbv, double precoJmbv, String marcaJmbv, Date validadeJmbv) {
        this.idprodutosJmbv = idprodutosJmbv;
        this.nomeJmbv = nomeJmbv;
        this.precoJmbv = precoJmbv;
        this.marcaJmbv = marcaJmbv;
        this.validadeJmbv = validadeJmbv;
    }
    
    
    
     @Id 

    
    @Column(name="idprodutos_jmbv", unique=true, nullable=false)
    public int getIdprodutosJmbv() {
        return this.idprodutosJmbv;
    }
    
    public void setIdprodutosJmbv(int idprodutosJmbv) {
        this.idprodutosJmbv = idprodutosJmbv;
    }

    
    @Column(name="nome_jmbv", nullable=false, length=70)
    public String getNomeJmbv() {
        return this.nomeJmbv;
    }
    
    public void setNomeJmbv(String nomeJmbv) {
        this.nomeJmbv = nomeJmbv;
    }

    
    @Column(name="preco_jmbv", nullable=false, precision=10)
    public double getPrecoJmbv() {
        return this.precoJmbv;
    }
    
    public void setPrecoJmbv(double precoJmbv) {
        this.precoJmbv = precoJmbv;
    }

    
    @Column(name="marca_jmbv", nullable=false, length=15)
    public String getMarcaJmbv() {
        return this.marcaJmbv;
    }
    
    public void setMarcaJmbv(String marcaJmbv) {
        this.marcaJmbv = marcaJmbv;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="validade_jmbv", nullable=false, length=10)
    public Date getValidadeJmbv() {
        return this.validadeJmbv;
    }
    
    public void setValidadeJmbv(Date validadeJmbv) {
        this.validadeJmbv = validadeJmbv;
    }


}


