package bean;
// Generated 12/09/2023 08:36:38 by Hibernate Tools 4.3.1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * UsuariosJmbv generated by hbm2java
 */
@Entity
@Table(name="usuarios_jmbv"
    ,catalog="db_joao_vilhanueva"
)
public class UsuariosJmbv  implements java.io.Serializable {


     private int idusuariosJmbv;
     private String nomeJmbv;
     private String apelidoJmbv;
     private String cpfJmbv;
     private Date dataNascimentoJmbv;
     private String senhaJmbv;
     private int nivelJmbv;
     private String ativoJmbv;

    public UsuariosJmbv() {
    }

	
    public UsuariosJmbv(int idusuariosJmbv, String nomeJmbv, String cpfJmbv, Date dataNascimentoJmbv, String senhaJmbv, int nivelJmbv, String ativoJmbv) {
        this.idusuariosJmbv = idusuariosJmbv;
        this.nomeJmbv = nomeJmbv;
        this.cpfJmbv = cpfJmbv;
        this.dataNascimentoJmbv = dataNascimentoJmbv;
        this.senhaJmbv = senhaJmbv;
        this.nivelJmbv = nivelJmbv;
        this.ativoJmbv = ativoJmbv;
    }
    public UsuariosJmbv(int idusuariosJmbv, String nomeJmbv, String apelidoJmbv, String cpfJmbv, Date dataNascimentoJmbv, String senhaJmbv, int nivelJmbv, String ativoJmbv) {
       this.idusuariosJmbv = idusuariosJmbv;
       this.nomeJmbv = nomeJmbv;
       this.apelidoJmbv = apelidoJmbv;
       this.cpfJmbv = cpfJmbv;
       this.dataNascimentoJmbv = dataNascimentoJmbv;
       this.senhaJmbv = senhaJmbv;
       this.nivelJmbv = nivelJmbv;
       this.ativoJmbv = ativoJmbv;
    }
   
     @Id 

    
    @Column(name="idusuarios_jmbv", unique=true, nullable=false)
    public int getIdusuariosJmbv() {
        return this.idusuariosJmbv;
    }
    
    public void setIdusuariosJmbv(int idusuariosJmbv) {
        this.idusuariosJmbv = idusuariosJmbv;
    }

    
    @Column(name="nome_jmbv", nullable=false, length=50)
    public String getNomeJmbv() {
        return this.nomeJmbv;
    }
    
    public void setNomeJmbv(String nomeJmbv) {
        this.nomeJmbv = nomeJmbv;
    }

    
    @Column(name="apelido_jmbv", length=25)
    public String getApelidoJmbv() {
        return this.apelidoJmbv;
    }
    
    public void setApelidoJmbv(String apelidoJmbv) {
        this.apelidoJmbv = apelidoJmbv;
    }

    
    @Column(name="cpf_jmbv", nullable=false, length=11)
    public String getCpfJmbv() {
        return this.cpfJmbv;
    }
    
    public void setCpfJmbv(String cpfJmbv) {
        this.cpfJmbv = cpfJmbv;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="dataNascimento_jmbv", nullable=false, length=10)
    public Date getDataNascimentoJmbv() {
        return this.dataNascimentoJmbv;
    }
    
    public void setDataNascimentoJmbv(Date dataNascimentoJmbv) {
        this.dataNascimentoJmbv = dataNascimentoJmbv;
    }

    
    @Column(name="senha_jmbv", nullable=false, length=20)
    public String getSenhaJmbv() {
        return this.senhaJmbv;
    }
    
    public void setSenhaJmbv(String senhaJmbv) {
        this.senhaJmbv = senhaJmbv;
    }

    
    @Column(name="nivel_jmbv", nullable=false)
    public int getNivelJmbv() {
        return this.nivelJmbv;
    }
    
    public void setNivelJmbv(int nivelJmbv) {
        this.nivelJmbv = nivelJmbv;
    }

    
    @Column(name="ativo_jmbv", nullable=false, length=1)
    public String getAtivoJmbv() {
        return this.ativoJmbv;
    }
    
    public void setAtivoJmbv(String ativoJmbv) {
        this.ativoJmbv = ativoJmbv;
    }




}


