package bean;
// Generated 14/11/2023 18:30:52 by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * VendasProdutoJmbv generated by hbm2java
 */
@Entity
@Table(name="vendas_produto_jmbv"
    ,catalog="db_joao_vilhanueva"
)
public class VendasProdutoJmbv  implements java.io.Serializable {


     private int idvendasProdutoJmbv;
     private ProdutosJmbv produtosJmbv;
     private VendasJmbv vendasJmbv;
     private double valorUnitarioJmbv;
     private int quantidadeJmbv;

    public VendasProdutoJmbv() {
    }

    public VendasProdutoJmbv(int idvendasProdutoJmbv, ProdutosJmbv produtosJmbv, VendasJmbv vendasJmbv, double valorUnitarioJmbv, int quantidadeJmbv) {
       this.idvendasProdutoJmbv = idvendasProdutoJmbv;
       this.produtosJmbv = produtosJmbv;
       this.vendasJmbv = vendasJmbv;
       this.valorUnitarioJmbv = valorUnitarioJmbv;
       this.quantidadeJmbv = quantidadeJmbv;
    }
   
     @Id 

    
    @Column(name="idvendas_produto_jmbv", unique=true, nullable=false)
    public int getIdvendasProdutoJmbv() {
        return this.idvendasProdutoJmbv;
    }
    
    public void setIdvendasProdutoJmbv(int idvendasProdutoJmbv) {
        this.idvendasProdutoJmbv = idvendasProdutoJmbv;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fkproduto_jmbv", nullable=false)
    public ProdutosJmbv getProdutosJmbv() {
        return this.produtosJmbv;
    }
    
    public void setProdutosJmbv(ProdutosJmbv produtosJmbv) {
        this.produtosJmbv = produtosJmbv;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="fkvendas_jmbv", nullable=false)
    public VendasJmbv getVendasJmbv() {
        return this.vendasJmbv;
    }
    
    public void setVendasJmbv(VendasJmbv vendasJmbv) {
        this.vendasJmbv = vendasJmbv;
    }

    
    @Column(name="valor_unitario_jmbv", nullable=false, precision=10)
    public double getValorUnitarioJmbv() {
        return this.valorUnitarioJmbv;
    }
    
    public void setValorUnitarioJmbv(double valorUnitarioJmbv) {
        this.valorUnitarioJmbv = valorUnitarioJmbv;
    }

    
    @Column(name="quantidade_jmbv", nullable=false)
    public int getQuantidadeJmbv() {
        return this.quantidadeJmbv;
    }
    
    public void setQuantidadeJmbv(int quantidadeJmbv) {
        this.quantidadeJmbv = quantidadeJmbv;
    }




}


