package bean;
// Generated 14/11/2023 18:30:52 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * VendasJmbv generated by hbm2java
 */
@Entity
@Table(name="vendas_jmbv"
    ,catalog="db_joao_vilhanueva"
)
public class VendasJmbv  implements java.io.Serializable {


     private int idvendasJmbv;
     private Date dataJmbv;
     private int clienteJmbv;
     private int vendedorJmbv;
     private double valorTotalJmbv;

    public VendasJmbv() {
    }

	
    public VendasJmbv(int idvendasJmbv, Date dataJmbv, int clienteJmbv, int vendedorJmbv, double valorTotalJmbv) {
        this.idvendasJmbv = idvendasJmbv;
        this.dataJmbv = dataJmbv;
        this.clienteJmbv = clienteJmbv;
        this.vendedorJmbv = vendedorJmbv;
        this.valorTotalJmbv = valorTotalJmbv;
    }
     @Id 

    
    @Column(name="idvendas_jmbv", unique=true, nullable=false)
    public int getIdvendasJmbv() {
        return this.idvendasJmbv;
    }
    
    public void setIdvendasJmbv(int idvendasJmbv) {
        this.idvendasJmbv = idvendasJmbv;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="data_jmbv", nullable=false, length=10)
    public Date getDataJmbv() {
        return this.dataJmbv;
    }
    
    public void setDataJmbv(Date dataJmbv) {
        this.dataJmbv = dataJmbv;
    }

    
    @Column(name="cliente_jmbv", nullable=false)
    public int getClienteJmbv() {
        return this.clienteJmbv;
    }
    
    public void setClienteJmbv(int clienteJmbv) {
        this.clienteJmbv = clienteJmbv;
    }

    
    @Column(name="vendedor_jmbv", nullable=false)
    public int getVendedorJmbv() {
        return this.vendedorJmbv;
    }
    
    public void setVendedorJmbv(int vendedorJmbv) {
        this.vendedorJmbv = vendedorJmbv;
    }

    
    @Column(name="valor_total_jmbv", nullable=false, precision=10)
    public double getValorTotalJmbv() {
        return this.valorTotalJmbv;
    }
    
    public void setValorTotalJmbv(double valorTotalJmbv) {
        this.valorTotalJmbv = valorTotalJmbv;
    }




}


