package bean;
// Generated 05/12/2023 09:11:09 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import tools.Util;

/**
 * VendasJmbv generated by hbm2java
 */
@Entity
@Table(name="vendas_jmbv"
    ,catalog="db_joao_vilhanueva"
)
public class VendasJmbv  implements java.io.Serializable {


     private int idvendasJmbv;
     private ClientesJmbv clientesJmbv;
     private VendedorJmbv vendedorJmbv;
     private Date dataJmbv;
     private double valorTotalJmbv;

    public VendasJmbv() {
    }

	
    public VendasJmbv(int idvendasJmbv, ClientesJmbv clientesJmbv, VendedorJmbv vendedorJmbv, Date dataJmbv, double valorTotalJmbv) {
        this.idvendasJmbv = idvendasJmbv;
        this.clientesJmbv = clientesJmbv;
        this.vendedorJmbv = vendedorJmbv;
        this.dataJmbv = dataJmbv;
        this.valorTotalJmbv = valorTotalJmbv;
    }
   
     @Id 

    
    @Column(name="idvendas_jmbv", unique=true, nullable=false)
    public int getIdvendasJmbv() {
        return this.idvendasJmbv;
    }
    
    public void setIdvendasJmbv(int idvendasJmbv) {
        this.idvendasJmbv = idvendasJmbv;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="cliente_jmbv", nullable=false)
    public ClientesJmbv getClientesJmbv() {
        return this.clientesJmbv;
    }
    
    public void setClientesJmbv(ClientesJmbv clientesJmbv) {
        this.clientesJmbv = clientesJmbv;
    }

@ManyToOne(fetch=FetchType.EAGER)
    @JoinColumn(name="vendedor_jmbv", nullable=false)
    public VendedorJmbv getVendedorJmbv() {
        return this.vendedorJmbv;
    }
    
    public void setVendedorJmbv(VendedorJmbv vendedorJmbv) {
        this.vendedorJmbv = vendedorJmbv;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="data_jmbv", nullable=false, length=10)
    public Date getDataJmbv() {
        return this.dataJmbv;
    }
    
    public void setDataJmbv(Date dataJmbv) {
        this.dataJmbv = dataJmbv;
    }

    
    @Column(name="valor_total_jmbv", nullable=false, precision=22, scale=0)
    public double getValorTotalJmbv() {
        return this.valorTotalJmbv;
    }
    
    public void setValorTotalJmbv(double valorTotalJmbv) {
        this.valorTotalJmbv = valorTotalJmbv;
    }
@Override
public String toString() {
    String id = Util.intStr(this.idvendasJmbv);
return id;
}
}


